/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/public/trust-marks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get trust mark proof
         * @description The public, server-backed proof a badge links to: verdict, method, issuer and verification date. No API key, no PII.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Proof */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            markId: string;
                            verdict: string;
                            method: string;
                            issuerRef: string | null;
                            verifiedAt: string;
                            relyingPartyName: string;
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify a credential
         * @description `byHash` verifies a registered credential by id; `byVC` verifies a portable VC-JWT (or selectively-disclosed SD-JWT presentation) from any issuer; `byZkTls` verifies a credential from a NON-integrated issuer via a zkTLS proof and Glemo's curated schema registry; `byImage` matches a credential image by hash and runs anti-fraud signal analysis (heuristics and EXIF). Every verdict includes an anti-fraud `risk` score.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        method: "byHash" | "byVC" | "byZkTls" | "byImage";
                        /** Format: uuid */
                        credentialId?: string;
                        jwt?: string;
                        /** @example coursera.org */
                        domain?: string;
                        proof?: {
                            /** @example reclaim */
                            engine: string;
                            /** @description Proof payload as produced by the zkTLS engine */
                            payload?: unknown;
                        };
                        /** @description Credential image (PNG/JPEG) or PDF, base64. Max 2 MB decoded. */
                        imageBase64?: string;
                    };
                };
            };
            responses: {
                /** @description Verdict */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status: string;
                            checks: {
                                name: string;
                                ok: boolean;
                            }[];
                            issuer?: string;
                            claims?: {
                                [key: string]: string;
                            };
                            /** @description Anti-fraud risk score 0-100. A signal, never a verdict override. */
                            risk?: {
                                score: number;
                                signals: string[];
                            };
                            /** @description Measured server-side verification time in milliseconds. */
                            latencyMs: number;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Monthly quota exceeded (block-policy plans). Upgrade to continue. */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden (missing scope or plan feature) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a credential
         * @description Issues a W3C VC 2.0 / Open Badges 3.0 credential (VC-JWT plus a selectively-disclosable SD-JWT), anchors it, and, for email recipients, delivers it with a public verification link. Recipients don't need a wallet: an email address is enough.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        recipient: {
                            /**
                             * Format: email
                             * @example ada@university.edu
                             */
                            email?: string;
                            /** @example did:web:alice.example.com */
                            did?: string;
                            /** @example Ada Lovelace */
                            name?: string;
                        };
                        achievement: {
                            /** @example Avalanche Fundamentals */
                            name: string;
                            description?: string;
                            criteria?: string;
                        };
                        /** Format: date-time */
                        validUntil?: string;
                        soulbound?: boolean;
                    };
                };
            };
            responses: {
                /** @description Credential issued */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            credentialId: string;
                            subjectId: string;
                            publicUrl: string;
                            jwt: string;
                            sdJwt: string;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/verifications/{credentialId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify a shared credential
         * @description No auth. Used by share links and QR codes. Rate-limited; the response never contains PII.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    credentialId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Verdict (not_found is a verdict, never 404) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status: string;
                            issuerDid: string | null;
                            validFrom: string | null;
                            validUntil: string | null;
                            checkedAt: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/credentials/{credentialId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public display data for a shared credential
         * @description No auth. Powers the public credential page: verdict + the shareable render (name, achievement, issuer, template). Rate-limited. Exposes no email, subjectId or subject DID.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    credentialId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Display payload (not_found is a status, never 404) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status: string;
                            credentialId: string;
                            display: {
                                recipientName: string | null;
                                achievementName: string | null;
                                issueDate: string | null;
                            };
                            render: {
                                background: string | null;
                                fields: {
                                    key: string;
                                    xPct: number;
                                    yPct: number;
                                    fontSizePx: number;
                                    weight: string;
                                    align: string;
                                    color: string;
                                }[];
                            } | null;
                            issuer: {
                                name: string | null;
                                logoUrl: string | null;
                                websiteUrl: string | null;
                                brandColor: string | null;
                                whiteLabel: boolean;
                            };
                            checks: {
                                name: string;
                                ok: boolean;
                            }[];
                            validFrom: string | null;
                            validUntil: string | null;
                            checkedAt: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/credentials/{credentialId}/disclosable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the selectively-disclosable fields of a shared credential
         * @description No auth. Powers the holder's selective-presentation UI: which achievement fields (name, description, criteria) can be revealed, with their values. Rate-limited. 404 when the credential has no SD-JWT.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    credentialId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Disclosable fields */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            disclosable: {
                                field: string;
                                value: string;
                            }[];
                        };
                    };
                };
                /** @description Credential not found or not selectively presentable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/credentials/{credentialId}/present": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a selective-disclosure presentation
         * @description No auth. The holder chooses which achievement fields to reveal; the response is an SD-JWT presentation that discloses ONLY those fields (hidden fields never travel). Rate-limited. 404 when the credential has no SD-JWT.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    credentialId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description Achievement fields to disclose. Unknown fields are ignored.
                         * @example [
                         *       "name"
                         *     ]
                         */
                        reveal: string[];
                    };
                };
            };
            responses: {
                /** @description SD-JWT presentation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            presentation: string;
                        };
                    };
                };
                /** @description Credential not found or not selectively presentable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandbox/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a sandbox key
         * @description Self-serve: returns a test API key plus one valid and one revoked sample credential. Rate-limited (5/hour per IP).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Test key + sample credential ids */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            apiKey: string;
                            credentials: {
                                valid: string;
                                revoked: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
